### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by flaumanis** [fidum/laravel-dashboard-vapor-metrics-tile#11]
Looks like some of the required packages are not available while installing 

> Failed to download chartisan/php from dist: The "https://api.github.com/repos/Chartisan/PHP/zipball/85d2352077800e9bcb411aec1ff7e4d23eef93a1" file could not be downloaded (HTTP/2 404 ):

**Comment by dmason30** [comment]
Yes it was taken down by a copyright strike. I haven't found the time to find a suitable replacement package or revert to v6 of that package. 

Reference https://github.com/ConsoleTVs/Charts/issues/1

**Comment by dmason30** [comment]
@flaumanis Tagged 3.0.0 that fixes this.
